### ISSUE TITLE
Add log rotation for ALBS docker compose services

### ISSUE THREAD

**Issue by zklevsha** [AlmaLinux/build-system#140]
Config [example](https://docs.docker.com/compose/compose-file/compose-file-v3/#logging) 
```
version: "3.8"
services:
  some-service:
    image: some-service
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
```

3 files by 100Mb max should be enough
