### ISSUE TITLE
vars.yaml is created as a directory nder alma-tests-cacher

### ISSUE THREAD

**Issue by metalefty** [AlmaLinux/build-system#168]
ref. https://github.com/AlmaLinux/build-system/issues/132#issuecomment-1898357643 

After [albs-deploy#10](https://github.com/AlmaLinux/albs-deploy/pull/10), it is still not working. `vars.yaml` is created as a directory for some reasons. I'm looking into this but for the record.

```
$ docker logs albs_test_cacher_1
Traceback (most recent call last):
  File "/code/alma_tests_cacher.py", line 27, in <module>
    asyncio.run(main())
  File "/usr/lib64/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/code/alma_tests_cacher.py", line 10, in main
    config = get_config()
  File "/code/alma_tests_cacher/utils.py", line 13, in get_config
    with open(config_path or DEFAULT_CONFIG_PATH, 'rt') as file:
IsADirectoryError: [Errno 21] Is a directory: 'vars.yaml'
```

```
$ ls -l
total 64
-rw-r--r--. 1 almalinux almalinux   623 Jan 23 07:30 Dockerfile
-rw-r--r--. 1 almalinux almalinux 34523 Jan 23 07:30 LICENSE
-rw-r--r--. 1 almalinux almalinux  1281 Jan 23 07:30 README.md
drwxr-xr-x. 3 almalinux almalinux   114 Jan 23 07:32 alma_tests_cacher
-rw-r--r--. 1 almalinux almalinux   731 Jan 23 07:30 alma_tests_cacher.py
-rw-r--r--. 1 almalinux almalinux   627 Jan 23 07:30 docker-compose.yml
-rw-r--r--. 1 almalinux almalinux   177 Jan 23 07:30 pyproject.toml
-rw-r--r--. 1 almalinux almalinux   104 Jan 23 07:30 requirements.txt
-rw-r--r--. 1 almalinux almalinux    66 Jan 23 07:30 test-requirements.txt
drwxr-xr-x. 2 almalinux almalinux    47 Jan 23 07:30 tests
drwxr-xr-x. 2 root      root          6 Jan 23 07:31 vars.yaml
```

**Comment by metalefty** [comment]
The `vars.yaml` directory will recreated again even if deleting manually so I guess the directory is created by docker container.

**Comment by metalefty** [comment]
`volumes` in docker-compose.yml creates `vars.yaml` directory if `vars.yaml` configuration file does not exist.

I will modify `albs-deploy` to prepare the configuration file. I think the name of the config file should be `tests_cacher.yml` or something because albs-deploy handles numbers of config files. `vars.yaml` is not clear.

```yaml
version: "3.9"
services:
  cacher:
    image: alma-tests-cacher:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - "./alma_tests_cacher:/code/alma_tests_cacher"
      - "./alma_tests_cacher.py:/code/alma_tests_cacher.py"
      - "./requirements.txt:/code/requirements.txt"
      - "./vars.yaml:/code/vars.yaml"
    command: "bash -c '/wait_for_it.sh web_server:8000 &&
              source env/bin/activate &&
              pip3 install --upgrade pip &&
              pip3 install -r /code/requirements.txt --no-cache-dir &&
              python alma_tests_cacher.py'"
```
