### ISSUE TITLE
deploy: alma-tests-cacher/vars.yaml not writable

### ISSUE THREAD

**Issue by metalefty** [AlmaLinux/build-system#343]
```
failed: [albs_on_one_vm] (item={'sname': 'alma-tests-cacher-vars.yaml.j2', 'dname': 'vars.yaml', 'dest': '~/albs/alma-tests-cacher', 'mode': '0644'}) => {
    "ansible_loop_var": "item",
    "changed": false,
    "checksum": "a66e991e4068785cf784b5269ac52cd235439d5c",
    "diff": [],
    "invocation": {
        "module_args": {
            "_original_basename": "alma-tests-cacher-vars.yaml.j2",
            "attributes": null,
            "backup": false,
            "checksum": "a66e991e4068785cf784b5269ac52cd235439d5c",
            "content": null,
            "dest": "/home/almalinux/albs/alma-tests-cacher/vars.yaml",
            "directory_mode": null,
            "follow": false,
            "force": true,
            "group": null,
            "local_follow": null,
            "mode": "0644",
            "owner": null,
            "remote_src": null,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": "/home/almalinux/.ansible/tmp/ansible-tmp-1726822499.238247-1722109-25746337306537/source",
            "unsafe_writes": false,
            "validate": null
        }
    },
    "item": {
        "dest": "~/albs/alma-tests-cacher",
        "dname": "vars.yaml",
        "mode": "0644",
        "sname": "alma-tests-cacher-vars.yaml.j2"
    }
}

MSG:

Destination /home/almalinux/albs/alma-tests-cacher/vars.yaml not writable
```

vars.yaml is a directory for some reasons.
```
total 64
-rw-r--r--. 1 almalinux almalinux   684 Sep 19 07:50 Dockerfile
-rw-r--r--. 1 almalinux almalinux 34523 Sep 19 07:50 LICENSE
-rw-r--r--. 1 almalinux almalinux  1329 Sep 19 07:50 README.md
drwxr-xr-x. 3 almalinux almalinux   114 Sep 20 08:40 alma_tests_cacher
-rw-r--r--. 1 almalinux almalinux   731 Sep 19 07:50 alma_tests_cacher.py
-rw-r--r--. 1 almalinux almalinux   325 Sep 19 07:50 docker-compose.yml
-rw-r--r--. 1 almalinux almalinux   866 Sep 19 07:50 pyproject.toml
-rw-r--r--. 1 almalinux almalinux   143 Sep 19 07:50 requirements-tests.txt
-rw-r--r--. 1 almalinux almalinux   103 Sep 19 07:50 requirements.txt
drwxr-xr-x. 2 almalinux almalinux    47 Sep 19 07:50 tests
drwxr-xr-x. 2 root      root          6 Sep 20 08:43 vars.yaml
```

The following definitions of volumes creates `vars.yaml` as a directory and it prevents to deploy generated_configs in `roles/dev_deploy/defaults/main/configs.yml`.

```
  tests_cacher:
    image: alma-tests-cacher:latest
    build:
      context: ../alma-tests-cacher
      dockerfile: Dockerfile
      target: cacher
    restart: on-failure
    volumes:
      - "../alma-tests-cacher/alma_tests_cacher:/code/alma_tests_cacher"
      - "../alma-tests-cacher/alma_tests_cacher.py:/code/alma_tests_cacher.py"
      - "../alma-tests-cacher/vars.yaml:/code/vars.yaml"
```
